"use client";

import { ImageAI } from "@/lib/imageAi";
import { PromptAI } from "@/lib/promptAi";
import { useState } from "react";

const promptAi = new PromptAI();
const imageAi = new ImageAI();

export default function Home() {
  const [prompt, setPrompt] = useState("");
  const [generatedText, setGeneratedText] = useState("");
  const [generatedImage, setGeneratedImage] = useState("");

  const handleGenerate = async () => {
    try {
      const text = await promptAi.generatePrompt(prompt);
      setGeneratedText(text);

      const imageUrl = await imageAi.generateImage(prompt);
      setGeneratedImage(imageUrl);
    } catch (error) {
      console.error("Error:", error);
    }
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <div className="z-10 w-full max-w-5xl items-center justify-between font-mono text-sm lg:flex">
        <div className="w-full">
          <div className="mb-8 w-full">
            <label
              htmlFor="prompt"
              className="block mb-2 text-sm font-medium text-gray-900 dark:text-white"
            >
              Start adding some description about your task for PDF
            </label>
            <textarea
              rows={10}
              id="prompt"
              className="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              placeholder="generate me a good looking document for my nextjs app"
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              required
            />
          </div>
          <button
            type="button"
            onClick={handleGenerate}
            className="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
          >
            Generate
          </button>
          {generatedText && (
            <div className="mt-8">
              <h3 className="text-lg font-medium">Generated Text:</h3>
              <p>{generatedText}</p>
            </div>
          )}
          {generatedImage && (
            <div className="mt-8">
              <h3 className="text-lg font-medium">Generated Image:</h3>
              <img src={generatedImage} alt="Generated by DALL-E" />
            </div>
          )}
        </div>
      </div>
    </main>
  );
}
