import { IPage } from "@/types"

export const PDFCard = ({ page }: { page: IPage }) => {
    return <div className="flex gap-x-8 mt-8 items-center">
        <div className="w-full sm:w-3/4">
            <p>{page.text}</p>
        </div>
        <div className="w-full sm:w-1/4">
            <img src={page.image} alt="Generated by DALL-E" className="w-full" />
        </div>
    </div>
}