import { OPEN_AI_API_KEY } from "@/constant/env";
import { ImageSize } from "@/types";
import OpenAI from "openai";

export class ImageAI {
    private openAI: OpenAI;
    private modelId: string;
    private systemPrompt: string;

    constructor() {

        this.modelId = "gpt-4o";
        this.systemPrompt = '';
        this.openAI = new OpenAI({
            apiKey: OPEN_AI_API_KEY,
            dangerouslyAllowBrowser: true,
        });
    }

    async generateImage(prompt: string, size: ImageSize, n: number) {
        try {
            const response = await this.openAI.images.generate({
                prompt: prompt,
                n,
                response_format: 'b64_json',
                size,
            });

            const imageUrl = response.data;
            if (imageUrl) {
                return imageUrl;
            } else {
                throw new Error("No image generated by DALL-E");
            }
        } catch (error) {
            console.error("Error generating image:", error);
            throw error;
        }
    }
}
